### ISSUE TITLE
Discussion: what's the relationship between rules_jvm and rules_java?

### ISSUE THREAD

**Issue by jschaf** [bazel-contrib/rules_jvm#210]
Hi all,

I'm starting to add Java support to an existing Bazel project. Would anyone mind outlining the differences between rules_jvm and rules_java?

Specifically, I'm trying to figure out:

* Do I use rules_java or rules_jvm? Is rules_jvm a replacement or complement to rules_java?
* Is rules_java "officially" supported?
* Gazelle support: I saw Gazelle support in rules_jvm, does it only work with rules_jvm?
* What's the future of rules_jvm? Will it keep up with bzlmod?

Happy to close or post elsewhere if you'd prefer.

**Comment by illicitonion** [comment]
All reasonable questions. Hopefully https://github.com/bazel-contrib/rules_jvm/pull/214 helps to clarify the situation.

Some specific answers:

> Do I use rules_java or rules_jvm? Is rules_jvm a replacement or complement to rules_java?

Complement - you should use `rules_java` wherever it makes sense. `rules_jvm` doesn't offer any _replacement_ functionality, but offers some additional functionality (e.g. support for running checkstyle, and wrapper macros you may want to wrap _around_ things like `java_library` to support grouping tests).

> Is rules_java "officially" supported?

Yes.

> Gazelle support: I saw Gazelle support in rules_jvm, does it only work with rules_jvm?

The Gazelle implementation mostly generates targets which use rules from rules_java, e.g. it will generate `java_library` and `java_binary` targets from `rules_java`. You can see [here](https://github.com/bazel-contrib/rules_jvm/blob/e384e30182b3f36ef2f324943e06567c7577af79/java/gazelle/lang.go#L130-L153) which rules it will generate - most are from `rules_java`, but rules_java's test runner only supports junit4 not junit5, so if you have junit5 tests, we will instead generate a rule from `rules_jvm` which supports junit5. If `rules_java` started supporting junit5 (and the other functionality of rules_jvm's testrunner), we'd probably delete the rules_jvm testrunner - we're not in the business of implementing things Just Because, everything in here has been implemented because it wasn't elsewhere, and it would be hard for us to add to `rules_java`.

> What's the future of rules_jvm?

Several major companies depend on it, so it is likely to continue being maintained, and it accepts contributions. You can see the minimal maintenance promises of rulesets in `bazel-contrib` [here](https://bazel-contrib.github.io/SIG-rules-authors/hosting-policy.html). But no guarantees are made.

> Will it keep up with bzlmod?

Yes, I believe rules_jvm currently fully supports bzlmod, and tests this in CI.
